### PR TITLE
rename to avoid conflic with real statsd

### PR DESCRIPTION
**Pull request by grosser**
@clutchski
 - Make it possible to use this while still having a real statsd
 - Make it obvious that we are using a modified statsd

### CODE REVIEW

**Comment by philihp** [comment]
Status?

**Comment by alq666** [comment]
@elafarge @yannmh long-standing PR that needs some closure, one way or another. Is there a similar path to datadogpy here?

**Comment by philihp** [comment]
This is a good change, however it is not backward-compatible and should increment increment the major version number.

**Comment by gphat** [comment]
:+1: on this!!

**Comment by parkr** [comment]
Would love to see this!

**Comment by degemer** [comment]
Thank you all for your patience, in `dogstatsd-ruby` 2.0.0 (released today), the `Statsd`  class is now under the `Datadog` namespace.
More details and full changelog: https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#200-20160922

**Pull request closed without merging**
