### PR TITLE
Migrate to CircleCI

### PR DESCRIPTION
**Pull request by remeh**

### CODE REVIEW

**Review by ivoanjo — APPROVED** [review]
If the plan is to drop 2.0 (good idea!), [we should also change the `gemspec` to match](https://github.com/DataDog/dogstatsd-ruby/blob/master/dogstatsd-ruby.gemspec#L28)

**Comment by remeh** [comment]
Since support has been dropped off `dd-tracer-rb`, I've followed the path because I think that it's our guideline, but I want to confirm with my team first. Thanks for the review!

**Comment by ivoanjo** [comment]
Goodbye 2.0 and thanks for all the fish ;)

**Comment by remeh** [comment]
@ivoanjo concerning 2.0 support: I'll add a warning in 5.3.0 + some deprecation notes in the README that we will drop its support in 5.4.0
Meanwhile; I've added a job capable of running the tests with latest ruby 2.0, it's failing here since it needs #211 first.

**Pull request merged**
