### PR TITLE
use faster time method

### PR DESCRIPTION
**Pull request by grosser**
... also makes the method more symmetric

pro: faster
con: not stubbed by timecop and not available on ruby <2.1

... let me know what you think, I can fix up the specs if you want the PR

### CODE REVIEW

**Comment by masci** [comment]
A bit concerned about dropping support for ruby < 2.1, let me ask product management. Any chance we can make this backward compatible (sorry not quite a rubyist here)?

**Comment by grosser** [comment]
updated, should work nicely now :)

**Comment by grosser** [comment]
please also check out the other PRs I made 💘

**Comment by masci** [comment]
Awesome, thanks!

**Pull request merged**
