### PR TITLE
Namespace the Statsd class on the datadog module.

### PR DESCRIPTION
**Pull request by djpate**
Otherwise you can't load it with any other type of statsd.

### CODE REVIEW

**Comment by remh** [comment]
Thanks a lot @djpate we'll review this shortly!

**Comment by grosser** [comment]
Is this ever going to happen ... can you just merge and declare 2.0 ?

**Comment by Rshomali** [comment]
I really need this to use Datadog for my project. Any estimate when this will be merged?

**Comment by grosser** [comment]
never ;)

**Comment by gphat** [comment]
Ping! This would be a good thing!

**Comment by irabinovitch** [comment]
@remh anything pending before we can merge?

**Comment by weppos** [comment]
I agree that this should be into a separate namespace. It would really nice to have this change merged and released.

**Comment by degemer** [comment]
Thank you all for your patience, `dogstatsd-ruby` 2.0.0 is out with this change! (PR was rebased in https://github.com/DataDog/dogstatsd-ruby/pull/32 and merged)

Changelog: https://github.com/DataDog/dogstatsd-ruby/blob/master/CHANGELOG.md#200-20160922

**Comment by djpate** [comment]
yay!

**Pull request closed without merging**
