### PR TITLE
remove bad argument after options

### PR DESCRIPTION
**Pull request by grosser**
@masci 

should be easy to update for consumers since it will fail with an argumenterror

### CODE REVIEW

**Comment by grosser** [comment]
should be good for 4.0 ... also got another PR and we can add frozen strings too 🎉

**Comment by grosser** [comment]
ready for merge!

**Comment by grosser** [comment]
needs a rebase on https://github.com/DataDog/dogstatsd-ruby/pull/78

**Comment by grosser** [comment]
rebased, ready to merge!

**Comment by gmmeyer** [comment]
🙌

**Pull request merged**
