### PR TITLE
Name Statsd Sender thread

### LINKED ISSUE #185: Set name of background threads?
Howdy 👋 

Recently I added names to `dd-trace-rb` background threads (https://github.com/DataDog/dd-trace-rb/pull/1366).

Would be really cool to do the same for dogstatsd, as it helps debugging, and we have plans to show and use thread names in the profiler as well.

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #185.

The naming is easy.  Let me know if there's a better way to write the test.

### CODE REVIEW

**Review by sgnn7 — APPROVED** [review]
@djmitche Seems reasonable to me but makes sense if you want @remeh / @ivoanjo to be the second pair of eyes on this.

**Comment by djmitche** [comment]
Thanks!  Yeah, an eye on the test would be good.

**Review by remeh — APPROVED** [review]
🙇

**Review by ivoanjo — APPROVED** [review]
Looks good! At some point in the future I hope to also expose thread naming in the profiler, so having it set for all Datadog libraries is ⭐️⭐️⭐️⭐️⭐️

**Pull request merged**
