### PR TITLE
Truncate long event messages by default

### PR DESCRIPTION
**Pull request by jackellenberger**
## What
Instead of raising a RuntimeError and dropping the event when its
formatted string version is greater than 8kb, make an effort to truncate
the message portion of the event down to a sendable size.

Add the option to disable this feature by passing in :truncate => false
to @statsd.event.

 ## Why
It's not acceptable to have a silent failure around a seemingly
arbitrary message length limitation, especially with Datadog's event
monitors being so feature poor. This would be less of a problem if you
could compose a monitor to query "has there been an error in the last 5
minutes, or has there not been a success in the last hour", but as it
currently stands silent failures are a big weakness for our Datadog
integration.

The C# client library [accepted](https://github.com/DataDog/dogstatsd-csharp-client/pull/22) a similar change, so it should fly in the ruby CL as well. That one did not truncate by default, and we can go that way, I just don't know what use case there is for trying and silently failing to send events.

 ## Questions for maintainers

This change updates the "header" of the event to show the size of the truncated message rather than the size of the original message. I made this choice under the assumption that there is some backend magic on Datadog's side that needs that header to be correct. If it's not the case, we could get rid of a bit of logic by just sending the original message's size.

Cheers!

### CODE REVIEW

**Comment by jackellenberger** [comment]
👋 I'm not sure who to @ to get a review on this

**Comment by kbogtob** [comment]
Hey, thanks for your PR! I will check internally about the header and come back to you really soon.

**Comment by jackellenberger** [comment]
@kbogtob Any news?

**Comment by kbogtob** [comment]
Hello,
Sorry for the delay. We are going to port the feature you developed to fit the code after the merge of the PR #138.
Thank you so much!

**Comment by dani-sc** [comment]
Hi @kbogtob, any update on when you will port this feature as you suggested?

**Comment by remeh** [comment]
Hey everyone. Once again, thank you for your contribution. 🙇 
We've released [v4.8.3](https://github.com/DataDog/dogstatsd-ruby/releases/tag/v4.8.3) which adds an option `truncate_if_too_long` to the event call to truncate the event when needed.

I close this PR, please reopen it if that is not fixing your issue.

**Pull request closed without merging**
