### PR TITLE
do not use .& syntax, for ruby compatibility

### LINKED ISSUE #243: Make #239 ruby-2.2 compatible
#239 fixed some poor error-handling, but did so in a way that's not ruby-2.2 compatible (see [pipeline](https://app.circleci.com/pipelines/github/DataDog/dogstatsd-ruby/109/workflows/7cf376f4-0e7c-452e-99bb-16153e023ad6/jobs/787)).  Let's expand that `.&` syntax to be compatible..

cc: @grosser

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #243 (I hope)

### CODE REVIEW

**Review by grosser — APPROVED** [review]
that works 👍

**Comment by grosser** [comment]
finally some CI :D

**Comment by grosser** [comment]
please add ruby 3.1 too

**Review by remeh — APPROVED** [review]
👍

**Pull request merged**
