### PR TITLE
Add unix socket support

### PR DESCRIPTION
**Pull request by sullerandras**
Continuation of https://github.com/DataDog/dogstatsd-ruby/pull/55
To test it locally i installed the new datadog agent to my Mac following [the instructions here](https://github.com/DataDog/datadog-agent) then used a simple ruby script like this:
```ruby
require './lib/datadog/statsd'
require 'time'
STDOUT.sync = true

socket_file = ENV['DD_DOGSTATSD_SOCKET'] || '/tmp/socket/statsd.socket'
puts "========> socket_file: #{socket_file}"

client = Datadog::Statsd.new(nil, nil, socket_path: socket_file)

loop do
  client.increment('whatever')
  sleep(1)
end
```
I tried all scenarios listed in the [testing guide](https://github.com/DataDog/datadog-agent/wiki/Unix-Domain-Sockets-support#testing-methodology) and it worked.

### CODE REVIEW

**Comment by sullerandras** [comment]
Ruby 1.9 seems to fail because of [this error](https://github.com/bundler/bundler/issues/3558).
Ruby 2.1 errors are strange. It works with older `bundler <= 1.11.2` and seems to fail with any newer bundler.

**Comment by xvello** [comment]
hi @sullerandras , thanks a lot for your contribution!

I'm tagging the library maintainers to help figure out how to fix the tests.

**Comment by xvello** [comment]
hi @sullerandras,

Could you please rebase on master, as tests are fixed now?

Regards

**Comment by masci** [comment]
@sullerandras tried to make tests on 2.1.10 pass with no success, do you have any idea what that could be? I think we can drop tests on jruby1.9 but 2.1 seems to work despite the tests :(

**Comment by sullerandras** [comment]
@masci It seems like MRI Ruby 2.1 comes with an embedded minitest 4.7.5 and `rake` uses that for running the specs. Minitest 5 is installed by `bundler` but it is not used.

**Comment by sullerandras** [comment]
@masci Changed to `:direct` loader and now it works with Ruby 2.1, but jruby still fails. Unfortunately i had to specify the spec file name so need to update this when adding more spec files.

**Comment by masci** [comment]
@sullerandras awesome, thanks! I think this is a good tradeoff for keeping 2.1 tests around.
Can you remove jruby from the CI? Not sure why we still keep it there....

**Pull request merged**
