### PR TITLE
Drop support for Ruby before 2.1.0

### LINKED ISSUE #228: Drop support for ruby<2.1.0
https://github.com/DataDog/dogstatsd-ruby/blob/ed04ca4ac4543c409a6fb2a5014c36fcc125371d/lib/datadog/statsd.rb#L107-L109

### PR DESCRIPTION
**Pull request by djmitche**
Fixes #228.

### CODE REVIEW

**Comment by djmitche** [comment]
#230 seems to be showing that at least one of our deps has a transitive dep on a version of webrick not available in Ruby-2.0.

**Review by marcotc — APPROVED** [review]
👍  Support for 2.0 has already been dropped by https://github.com/DataDog/dd-trace-rb/releases/tag/v0.50.0 in Jun 2021.

**Review by remeh — APPROVED** [review]
LGTM.

Gems tend to drop Ruby versions in major releases, and note that a while back I've added this section in the README: https://github.com/DataDog/dogstatsd-ruby#versioning for us to be able to use a minor if we would prefer (we may drop multiple versions of Ruby in the future and we probably won't want to have multiple majors of `dogstatsd-ruby`).

I think we should mention somewhere (in the CHANGELOG update?) which version of `dogstatsd-ruby` is the last one to support Ruby 2.0. WDYT?

**Comment by marcotc** [comment]
> I think we should mention somewhere (in the CHANGELOG update?) which version of dogstatsd-ruby is the last one to support Ruby 2.0. WDYT?

If you go this way, we have an example of listing support for older Rubies in the documentation: https://github.com/DataDog/dd-trace-rb/blob/279ff50/docs/GettingStarted.md#compatibility. The matrix will likely be more simplified here, but I wanted to show you what we are doing today, in case it helps.

**Comment by djmitche** [comment]
https://github.com/DataDog/dogstatsd-ruby/blob/ed04ca4ac4543c409a6fb2a5014c36fcc125371d/lib/datadog/statsd.rb#L107-L109 did mention the deprecation.  I'll add a note to the README.

**Pull request merged**
