### PR TITLE
test on ruby 3.1

### PR DESCRIPTION
**Pull request by grosser**
fixes https://github.com/DataDog/dogstatsd-ruby/issues/246

### CODE REVIEW

**Comment by djmitche** [comment]
Ah, it looks like that's a warning, and the actual issue is
```
tereshkova ~ $ docker pull circleci/ruby:3.1-node
Error response from daemon: manifest for circleci/ruby:3.1-node not found: manifest unknown: manifest unknown
```
It looks like https://hub.docker.com/r/cimg/ruby is the new image.  I'll make a push to use that instead.

**Comment by grosser** [comment]
needs a rebase ... or just merge since it does not change the build status

**Comment by djmitche** [comment]
I'll rebase.

**Comment by djmitche** [comment]
Oh, I can't .. and I think it's fine as-is?  The `instance&.close` change hasn't been merged yet either.  Hopefully @remeh can review soon.

**Comment by grosser** [comment]
can just merge 🤷

**Review by remeh — APPROVED** [review]
Thanks for that addition!

@djmitche ~~we have to look into why you were not able to rebase if that was a permission thing 😅~~

I've merged the `instance&.close`, merging this as well now.

**Comment by djmitche** [comment]
It's because it's @grosser's branch - expected :)

**Pull request merged**
